### ISSUE TITLE
Huggingface Demo

### ISSUE THREAD

**Issue by khawar-islam** [haha-lisa/RDM-Region-Aware-Diffusion-Model#6]
Hello @haha-lisa 

Thanks for your work. Your huggingface demo is not working, please have a look on it

**Comment by haha-lisa** [comment]
Hi, our huggingface demo was developed for free with the help of others, and it seems to be a common problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haha-lisa/RDM-Region-Aware-Diffusion-Model"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 上午8:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[haha-lisa/RDM-Region-Aware-Diffusion-Model] Huggingface Demo (Issue #6)





 
Hello @haha-lisa
 
Thanks for your work. Your huggingface demo is not working, please have a look on it
