### ISSUE TITLE
关于论文与代码的一点疑惑

### ISSUE THREAD

**Issue by mycfhs** [haha-lisa/RDM-Region-Aware-Diffusion-Model#7]
请问这个项目是否已经完成？我看过作者您的RDM论文了，感觉有很多地方都和代码对不上，比如潜变量使用mask裁剪拼接、潜变量使用ldm进行去噪，以及mask的获取等方法。是我没有找到对应代码吗？还是该项目尚未完成？

**Comment by haha-lisa** [comment]
***@***.***，我晚些回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haha-lisa/RDM-Region-Aware-Diffusion-Model"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月9日(星期二) 下午3:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[haha-lisa/RDM-Region-Aware-Diffusion-Model] 关于论文与代码的一点疑惑 (Issue #7)





 
请问这个项目是否已经完成？我看过作者您的RDM论文了，感觉有很多地方都和代码对不上，比如潜变量使用mask裁剪拼接、潜变量使用ldm进行去噪，以及mask的获取等方法。是我没有找到对应代码吗？还是该项目尚未完成？

**Comment by mycfhs** [comment]
好滴好滴



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nisha ***@***.***&gt;; 
发送时间: 2024年1月9日(星期二) 下午3:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [haha-lisa/RDM-Region-Aware-Diffusion-Model] 关于论文与代码的一点疑惑 (Issue #7)





 ***@***.***，我晚些回复 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "haha-lisa/RDM-Region-Aware-Diffusion-Model"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年1月9日(星期二) 下午3:30 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[haha-lisa/RDM-Region-Aware-Diffusion-Model] 关于论文与代码的一点疑惑 (Issue #7) 
 
 
 
 
 
   
 请问这个项目是否已经完成？我看过作者您的RDM论文了，感觉有很多地方都和代码对不上，比如潜变量使用mask裁剪拼接、潜变量使用ldm进行去噪，以及mask的获取等方法。是我没有找到对应代码吗？还是该项目尚未完成？
